#!/command/with-contenv bash

# Load container functions and initialize process name
source /assets/functions/00-container
output_off
PROCESS_NAME="firewall"

# Prepare service and validate initialization
prepare_service defaults single
check_container_initialized
check_service_initialized init

liftoff

# Delay startup of Fail2ban to allow logs to populate
print_debug "Sleeping for '${FAIL2BAN_STARTUP_DELAY}' seconds before starting Fail2ban to ensure logs are populated"
sleep ${FAIL2BAN_STARTUP_DELAY}

# Start Fail2ban service
print_start "Starting Fail2ban"

if [ "${FAIL2BAN_LOG_TYPE,,}" = "file" ] ; then
    # If logs are stored in a file, enable output
    output_on
    silent exec fail2ban-server -f
else
    # If logs are not stored in a file, directly execute Fail2ban
    output_on
    exec fail2ban-server -f
fi
